In [6]:
import torch
import numpy as np 

In [7]:
#vector multiplication
a = torch.tensor(np.arange(0,10))
b = torch.tensor(np.arange(10,20))
a*b

tensor([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171], dtype=torch.int32)

In [8]:
#matrix multiplication
c = np.random.randint(0,10, size = (3,2))
d = np.random.randint(0,10, size = (2,3))

torch.tensor(c)@torch.tensor(d)

tensor([[72, 56, 56],
        [46, 35, 39],
        [60, 42, 66]], dtype=torch.int32)

In [9]:
torch.tensor(c.T)*torch.tensor(d)

tensor([[72, 35, 42],
        [ 0,  0, 24]], dtype=torch.int32)

In [12]:
#softmax 
a = torch.Tensor(np.arange(10))
print(a)
print(np.exp(a)/sum(np.exp(a)))
sm = torch.nn.Softmax(dim =0)
print(sm(a))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
        3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01])
tensor([7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
        3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01])


In [32]:
#entropy
p = torch.Tensor([0.2,0.5,0.75])
q = 1-p

entpy = -(p*torch.log(p) + q*torch.log(q))
entpy

tensor([0.5004, 0.6931, 0.5623])

In [171]:
#binary entropy 
prob = torch.Tensor([0.75,0.25,0.9])
bin_entropy = -torch.mean((prob*torch.log(prob))+((1-prob)*torch.log(1-prob)))
bin_entropy

tensor(0.4833)

In [168]:
#binary cross entropy
actual = torch.Tensor([1,0,1,1])
predicted = torch.Tensor([0.25,0.75,0.25,0.55])
actual_ = 1-actual
predicted_ = 1-predicted
bce = -torch.mean(actual*torch.log(predicted)+actual_*torch.log(predicted_))
bce

tensor(1.1892)

In [169]:
torch.nn.functional.binary_cross_entropy(predicted,actual)

tensor(1.1892)

In [172]:
#min max / argmin argmax
a = torch.tensor([2,3,1,4,5])

#value
torch.min(a), torch.max(a)

(tensor(1), tensor(5))

In [175]:
#position
torch.argmax(a), torch.argmin(a) 

(tensor(4), tensor(2))

In [184]:
#matrix 

a = np.random.randint(0,10,size=(3,4))

print(a)
print('\n\nmin',np.min(a),'\n\nargmin_1', np.argmin(a,axis=1),'\n\nargmin_0', np.argmin(a,axis=0))

[[5 9 3 2]
 [7 7 3 8]
 [1 6 3 6]]


min 1 

argmin_1 [3 2 0] 

argmin_0 [2 2 0 0]


In [191]:
tensor_a = torch.tensor(a)
print('\n\nmin',tensor_a)
print('\n\nargmin0',torch.min(tensor_a,axis=0))
print('\n\nargmin1',torch.min(tensor_a,axis=1))




min tensor([[5, 9, 3, 2],
        [7, 7, 3, 8],
        [1, 6, 3, 6]], dtype=torch.int32)


argmin0 torch.return_types.min(
values=tensor([1, 6, 3, 2], dtype=torch.int32),
indices=tensor([2, 2, 0, 0]))


argmin1 torch.return_types.min(
values=tensor([2, 3, 1], dtype=torch.int32),
indices=tensor([3, 2, 0]))


In [200]:
#seeding 
print(np.random.randn(5))
print(np.random.randn(5))

# [ 0.40234471  0.31096427  0.22816184 -1.64422623 -0.75369468]
# [-0.86243225  0.86652576 -1.06436757  1.75543543  0.40017803]


[-0.47439702 -0.30191524 -0.93102638  1.11098606 -0.18968296]
[ 1.27840959 -0.55407712  0.35430274 -0.44027617 -0.42444883]


In [220]:
#seeding 
n1 = np.random.RandomState(45)
n2 = np.random.RandomState(458)
print(n1.randn(5))
print(n2.randn(5))

# [ 0.02637477  0.2603217  -0.39514554 -0.20430091 -1.27163265]
# [-2.59687863  0.28968091 -0.87330464  0.39407266  0.93510554]

[ 0.02637477  0.2603217  -0.39514554 -0.20430091 -1.27163265]
[-0.38406734 -0.55788836 -0.57974659  1.60780189  1.64720729]


In [224]:
print(n1.randn(5))
print(n2.randn(5))

[-0.49505193 -1.00860081  0.02524419 -0.12150685 -1.54687318]
[ 0.3359656   0.43537901  0.3660313  -0.30310544  0.92735241]


In [221]:
n1 = np.random.RandomState(45)
n2 = np.random.RandomState(458)
print(n1.randn(5))
print(n2.randn(5))

[ 0.02637477  0.2603217  -0.39514554 -0.20430091 -1.27163265]
[-0.38406734 -0.55788836 -0.57974659  1.60780189  1.64720729]
